services:
  laudos_local_db:
    container_name: laudos_local_db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-test}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dump:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
